# IMPORTANT: In production, use AWS Secrets Manager or External Secrets Operator
# This is for lab purposes only — never commit real credentials to Git!
apiVersion: v1
kind: Secret
metadata:
  name: novamart-db-secret
  namespace: novamart-ns
type: Opaque
stringData:
  DB_USERNAME: "novamart_admin"
  DB_PASSWORD: "Modesola123"
