apiVersion: v1
kind: Service
metadata:
  name: novamart-service
  namespace: novamart-ns
  labels:
    app: novamart
spec:
  type: LoadBalancer
  selector:
    app: novamart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
